### ISSUE TITLE
[bug] - Completou a palavra sem preencher todas as letras

### ISSUE THREAD

**Issue by jhonatasmatos** [willypedroso/hangman-game#1]
Olá 😄 

Primeiramente parabens pelo projeto ficou bem legal !!!
Gastei alguns minutos aqui brincando com ele rs, porém percebi um bug (não sei se proposital) mas quando digital o primeiro "S" da palavra CSS ele ja logo diz que acertamos a palavra antes mesmo de digitar o segundo "S", sabemos que se for "CS" a proxima letra será o "S", mas esse comportamento só ficou assim para essa palavra.

Abraço e e continue a evoluir 🚀

**Comment by willypedroso** [comment]
Muito obrigado pelo feedback! Na realidade essa questão da palavra "CSS" não  é um bug, é apenas como o jogo original funciona. Uma vez que a pessoa acerta uma letra, essa letra é preenchida em seus devidos lugares, por exemplo se a pessoa tentar a letra "A" em "JAVASCRIPT", não faz sentido que preencha apenas o primeiro "A" da palavra, entende? No caso do "CSS" por ter apenas três letras sendo duas delas iguais, o usuário só precisa acertar duas letras. Sendo assim, se o usuário já acertou a letra "C" ao tentar a letra "S" automaticamente ele acertou a palavra, pois não seria justa preencher apenas um "S" sendo que o usuário acertou a letra que falta. Mas mesmo assim, obrigado pela observação e pelo incentivo!

**Comment by jhonatasmatos** [comment]
Putz verdade!

Esqueci desse detalhe que ao acertar a letra ele preenche todos os locais em que essa letra existe.
